# Replace this with the name of the GNU compiler base image
FROM EDIT_BASEIMAGE

# First, copy hello.c from the host into the container
COPY sources/hello.c /var/tmp/hello.c

# Then compile the source code: gcc -o /var/tmp/hello /var/tmp/hello.c
RUN gcc -o /var/tmp/hello /var/tmp/hello.c

